import { atom, useAtomValue, useSetAtom } from 'jotai';
import { useCallback } from 'react';

/**
 * Todo ids whose titles are being generated by the backend right now.
 * Fed by the `title_generation_started/finished` change types on the
 * `todos:changed` event; read by TaskDetail to show the autotitle spinner.
 */
export const pendingTitleGenerationTodoIdsAtom = atom<ReadonlySet<number>>(
  new Set<number>(),
);

export function useTitleGenerationTracking(): {
  pendingTitleGenerationTodoIds: ReadonlySet<number>;
  onTitleGeneration: (todoId: number, pending: boolean) => void;
} {
  const pendingTitleGenerationTodoIds = useAtomValue(pendingTitleGenerationTodoIdsAtom);
  const setPending = useSetAtom(pendingTitleGenerationTodoIdsAtom);
  const onTitleGeneration = useCallback(
    (todoId: number, pending: boolean) => {
      setPending((current) => withTitleGenerationPending(current, todoId, pending));
    },
    [setPending],
  );

  return { pendingTitleGenerationTodoIds, onTitleGeneration };
}

export function withTitleGenerationPending(
  current: ReadonlySet<number>,
  todoId: number,
  pending: boolean,
): ReadonlySet<number> {
  if (pending === current.has(todoId)) {
    return current;
  }

  const next = new Set(current);
  if (pending) {
    next.add(todoId);
  } else {
    next.delete(todoId);
  }
  return next;
}
